linters:
  enable:
    - cyclop
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - grouper
    - maintidx
    - misspell

linters-settings:
  cyclop:
    skip-tests: true
    max-complexity: 15
    package-average: 0
  funlen:
    lines: -1
    statements: 100
