[package]
name = "trust"
version = "0.1.0"
authors = ["Zelalem Mekonen <zola@programmer.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frank_jwt = "3.1.1"
rocket = "0.4.1"
diesel = { version = "1.4.0", features = ["postgres", "mysql"] }
dotenv = "0.14.1"
serde = { version = "1.0", features = ["derive"]}
envy = "0.4"